services:
  stage4-linux:
    build: .
    container_name: stage4-linux
    restart: unless-stopped
    ports:
      - "192.168.56.20:2222:2222"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    networks:
      - stage4_net

networks:
  stage4_net:
    driver: bridge